version: '3'

services:
 db:
  build: 
   context: ./mysql
  command: --innodb-use-native-aio=0
  container_name: db
  restart: always
  tty: true
  volumes:
   - ./mysql/database:/var/lib/mysql
  environment:
   - MYSQL_DATABASE=nodedb
   - MYSQL_ROOT_PASSWORD=root
  networks:
   - node-network

 app:
  build:
   context: ./node
   dockerfile: Dockerfile
  container_name: app
  depends_on:
   - db
  entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm run start"
  networks:
   - node-network
  volumes:
   - ./node:/usr/src/app
  tty: true
  ports: 
   - "3000:3000"

 nginx:
  build:
   context: ./nginx
   dockerfile: Dockerfile
  container_name: nginx
  restart: always
  depends_on:
   - app
  ports: 
   - '8080:80'
  networks:
   - node-network

networks:
 node-network:
  driver: bridge